name: Release Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: xor_crypt-linux
            binary_path: target/release/xor_crypt
          - os: windows-latest
            artifact_name: xor_crypt-windows.exe
            binary_path: target/release/xor_crypt.exe
          - os: macos-latest
            artifact_name: xor_crypt-macos
            binary_path: target/release/xor_crypt

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Build release
      run: cargo build --release

    - name: Prepare asset name
      shell: bash
      run: |
        cp ${{ matrix.binary_path }} ${{ matrix.artifact_name }}

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ matrix.artifact_name }}
